### ISSUE TITLE
Log screen

### ISSUE THREAD

**Issue by binhmuc** [shaoniangu/FashionAI_Keypoint_Detection_Using_CPM#2]
I use learning rate is 0.4 and log screen is 
Step: 682/800000 ----- Cur_lr: 0.4000000 ----- Time: 0.82 sec.
S1 loss:     nan | S2 loss:     nan | S3 loss:     nan | S4 loss:     nan | S5 loss:     nan | S6 loss:   25.47 | Total loss: na
Total loss : nan.
I also try 0.01, 0.004 but fail :(

**Comment by shaoniangu** [comment]
Hi. Thank you for your issue. We did not set our learning rate in our repo but we will update it later. The NAN maybe caused by large grad at early epoch. The base learning rate in our task is set as 0.0002 with a warm up stage and a decay stage same with the warm up learning rate mechanism. You can try this. And CPM is supposed to converge easily. You can also do some visualization to make sure you generate your   train samples well.

**Comment by binhmuc** [comment]
Thank for your reply, it help me a lot, i finish learning rate, if you want, i can update in this repo. :D

**Comment by shaoniangu** [comment]
OK，you can make a pull request. Thanks a lot.
